### ISSUE TITLE
New settings - Author can only close a thread, not reopen

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/OP-can-close-thread#2]

**Comment by lairdshaw** [comment]
~~Are you still having this problem? I seem to have lost track of this issue, but I'm not aware of any ongoing problem to this effect - nobody else has reported it.~~

**Comment by lairdshaw** [comment]
Oh, wait. I misread. Sorry, and nevermind. I'll try to remember to implement this setting for the next release.

**Comment by Eldenroot** [comment]
Hi, OK .)
