### ISSUE TITLE
How to avoid bypassing moderators?

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/OP-can-close-thread#3]
What if a moderator closed the thread, but the author reopen it again? Is possible to override the permission if the thread is closed by selected usergroup then it is not possible to reopen it?

**Comment by lairdshaw** [comment]
If a moderator closes a thread, it is impossible for the author to reopen it again. If in your testing you find that the author *can* reopen threads closed by a moderator, then you've discovered a bug!
